# Generated by Django 4.1.5 on 2023-01-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('emailaddress', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vetfirstname', models.CharField(max_length=40, verbose_name='Vet name')),
                ('vetlastname', models.CharField(max_length=40, verbose_name='Vet lastname')),
                ('vetemailaddress', models.EmailField(max_length=200, verbose_name='Vet email')),
                ('vetspecialism', models.CharField(choices=[('SA', 'Small Animal'), ('AV', 'Avian'), ('RP', 'reptile'), ('EX', 'exotic'), ('CF', 'Canine and feline')], default='CF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=50, verbose_name='Pet Name')),
                ('petbreed', models.CharField(max_length=25, verbose_name='Pet Breed')),
                ('petage', models.IntegerField(verbose_name='Pet age')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.customer')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.vet')),
            ],
        ),
    ]
